version: "3"
services:
  nginx:
    image: "nginx"
    container_name: "blind-nginx"
    ports:
      - "3332:80"
    volumes:
      - "./src:/project"
      - "./config/nginx:/etc/nginx/conf.d"
  phpfpm:
    # image: 'sclecons/phpfpm:7.4'
    build: "src"
    container_name: "blind-php"
    volumes:
      - "./src:/project"
    ports:
      - "9000:9000"
  mysql:
    image: "mysql:8.0"
    container_name: "blind-mysql"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blind"
      MYSQL_USER: "blind"
      MYSQL_PASSWORD: "blind"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
  phpmyadmin:
    image: "phpmyadmin:latest"
    container_name: "blind-phpmyadmin"
    ports:
      - "9500:80"
    environment:
      PMA_ARBITRARY: 1
    restart: "always"